root = "." # Project root directory
tmp_dir = "tmp" # Folder for air's temporary files

[build]
    bin = "main" # Generated binary file name
    cmd = "go build -o {{.Output}} {{.Input}}" # Command to build the binary
    exclude = ["tmp/*", "client/*"] # Exclude files from monitoring
    include = ["**/*.go"] # Include files for monitoring
    ignore = ["tmp/*"] # Ignore during build
    