name: Go-ToDo
services:
  mongodb:
      image: mongo
      container_name: mongodb
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER:-root}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-password}
      volumes:
        - ./mongo_data:/data/mongodb
      ports:
        - 27017:27017
      restart: unless-stopped
      
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGODB_EXPRESS_USER:-root}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGODB_EXPRESS_PASSWORD:-password}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USER:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD:-password}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8081:8081
    restart: unless-stopped